--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Henry12960/Compact
build-by-default: true
branches:
- main
projects:
  Compact:
    path: ""
    icon: "Compact.png"
    libs:
      - src: https://poggit.pmmp.io/ci/Vecnavium/FormsUI/FormsUI    
...